/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.acidmanic.cicdassistant.wiki.convert;

import java.util.HashMap;

/**
 *
 * @author diego
 */
public class InMemoryResources {

    public static final HashMap<String, String> NAMED_THEMES = new HashMap<>();
    public static final HashMap<String, String> NAMED_THEMES_FLAGS = new HashMap<>();

    public static final String COPY_TO_CLIPBOARD_JS = "<script>\n"
            + "function copyToClipboard(id) {\n"
            + "  var copyText = document.getElementById(id);\n"
            + "  copyText.select();\n"
            + "  copyText.setSelectionRange(0, 99999)\n"
            + "  document.execCommand(\"copy\");\n"
            + "  console.log('id'+' Copied');\n"
            + "}\n"
            + "</script>";

    public static final String TOAST_COMPONENT = "<script>"
            + "function toastComponent(id){\n"
            + "    var component = document.getElementById(id);\n"
            + "    component.style.visibility='visible';\n"
            + "    component.style.opacity = 1;\n"
            + "    var fadeEffect = setInterval(function () {\n"
            + "        if (!component.style.opacity) {\n"
            + "            component.style.opacity = 1;\n"
            + "        }\n"
            + "        if (component.style.opacity > 0) {\n"
            + "            component.style.opacity -= 0.1;\n"
            + "        } else {\n"
            + "            clearInterval(fadeEffect);\n"
            + "             component.style.visibility='hidden';\n"
            + "        }\n"
            + "    }, 80);"
            + "}"
            + "</script>";

    public static final String WIKI_STYLES_GREEN
            = "body{\n"
            + "    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Noto Sans\", Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\n"
            + "    background-color:  #212622;\n"
            + "    color:#dadae3;\n"
            + "    padding-left: 5%;\n"
            + "    padding-right: 5%;\n"
            + "}\n"
            + "a,a:hover {\n"
            + "    text-decoration: none;\n"
            + "    font-weight: bolder;\n"
            + "    color: #18c8bb;\n"
            + "    text-shadow: 0 0 10px #0003c86e;\n"
            + "    vertical-align: top;\n"
            + "}\n"
            + "table {\n"
            + "    max-width: 60%;\n"
            + "    font-size: 0.9em;\n"
            + "    display: inline-table;\n"
            + "}\n"
            + "td {\n"
            + "    padding: 6pt;\n"
            + "}\n"
            + "thead{\n"
            + "    background: #09090987;\n"
            + "}\n"
            + "thead tr,thead td {\n"
            + "\n"
            + "\n"
            + "}\n"
            + "\n"
            + "tr{\n"
            + "    border: solid 1px #a2aab0;\n"
            + "    padding: 6pt;\n"
            + "}\n"
            + "tr:nth-child(even) {\n"
            + "    background: #4d7d7d80;\n"
            + "}\n"
            + "tr:nth-child(odd) {\n"
            + "    background: #46515180;\n"
            + "}\n"
            + "h1{\n"
            + "\n"
            + "}\n"
            + ".json-string{\n"
            + "    color: #62bb78;\n"
            + "}\n"
            + ".json-number{\n"
            + "    color: #fff890;\n"
            + "}\n"
            + ".json-number{\n"
            + "    color: #e89d5b;\n"
            + "}\n"
            + ".json-key{\n"
            + "    color: #a1b2f4;    \n"
            + "}\n"
            + ".json-object,code{\n"
            + "    background: #2b2f2f;\n"
            + "    border: solid 1px #a2aab0;\n"
            + "    font-size: 1em;\n"
            + "    display: inline-block;\n"
            + "    padding: 5pt;\n"
            + "}\n"
            + ".btn-copy, .btn-copy:active{\n"
            + "    width: 27pt;\n"
            + "    height: 13pt;\n"
            + "    border-radius: 3pt;\n"
            + "    float: right;\n"
            + "    margin: 0;\n"
            + "    border: solid 1px #7b7b7b;\n"
            + "    cursor: pointer;\n"
            + "    text-align: center;\n"
            + "    font-size: 9pt;\n"
            + "    color: #1a8cf0;\n"
            + "}\n"
            + ".btn-copy:active{\n"
            + "    background-color: #2d3233;\n"
            + "    text-shadow: 0px 0px 3pt #3b8a65;\n"
            + "    border: solid 1px #535353;\n"
            + "}\n"
            + ".hidden-data{\n"
            + "    width: 0px;\n"
            + "    height: 0px;\n"
            + "    position: absolute;\n"
            + "    top:0px;\n"
            + "    left: 0px;\n"
            + "    border: none;\n"
            + "    outline: none;\n"
            + "    margin: 0px;\n"
            + "    padding: 0px;\n"
            + "}\n"
            + ".code-message{\n"
            + "    display: block;\n"
            + "    visibility: hidden;\n"
            + "    padding-top: -2pt;\n"
            + "    margin-right: 20pt;\n"
            + "    margin-bottom: 6pt;\n"
            + "    color: #dbffe8;\n"
            + "    background-image: linear-gradient(to right, #4fac9fa3 , #62ff0a0a);\n"
            + "    text-align: center;\n"
            + "    padding-bottom: 2pt;\n"
            + "    padding-top: 2pt;\n"
            + "    border-radius: 3pt;\n"
            + "}\n"// added
            + ".theme-item {\n"
            + "    height: 3pt;\n"
            + "    color: white;\n"
            + "    width: 20pt;\n"
            + "    position: relative;\n"
            + "}\n"
            + ".theme-item:hover {\n"
            + "    height: 20pt;\n"
            + "    border: 1px solid #aab1b7;\n"
            + "    border-radius: 20pt;\n"
            + "}"
            + ".theme-container {\n"
            + "    cursor: pointer;\n"
            + "    left: 5pt;\n"
            + "    top: 5pt;\n"
            + "    position: absolute;\n"
            + "    display: block;\n"
            + "}";

    public static final String WIKI_STYLES_BLUE
            = "body{\n"
            + "    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Noto Sans\", Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\n"
            + "    background-color:  #212526;\n"
            + "    color:#dadae3;\n"
            + "    padding-left: 5%;\n"
            + "    padding-right: 5%;\n"
            + "}\n"
            + "a,a:hover {\n"
            + "    text-decoration: none;\n"
            + "    font-weight: bolder;\n"
            + "    color: #74c1d2;\n"
            + "    text-shadow: 0 0 10px #b4b5df6e;\n"
            + "    vertical-align: top;\n"
            + "}\n"
            + "table {\n"
            + "    max-width: 60%;\n"
            + "    font-size: 0.9em;\n"
            + "    display: inline-table;\n"
            + "}\n"
            + "td {\n"
            + "    padding: 6pt;\n"
            + "}\n"
            + "thead{\n"
            + "    background: #09090987;\n"
            + "}\n"
            + "thead tr,thead td {\n"
            + "\n"
            + "\n"
            + "}\n"
            + "\n"
            + "tr{\n"
            + "    border: solid 1px #a2aab0;\n"
            + "    padding: 6pt;\n"
            + "}\n"
            + "tr:nth-child(even) {\n"
            + "    background: #3c51795e;\n"
            + "}\n"
            + "tr:nth-child(odd) {\n"
            + "    background: #4e596480;\n"
            + "}\n"
            + "h1{\n"
            + "\n"
            + "}\n"
            + ".json-string{\n"
            + "    color: #62bb78;\n"
            + "}\n"
            + ".json-number{\n"
            + "    color: #fff890;\n"
            + "}\n"
            + ".json-number{\n"
            + "    color: #e89d5b;\n"
            + "}\n"
            + ".json-key{\n"
            + "    color: #a1b2f4;    \n"
            + "}\n"
            + ".json-object,code{\n"
            + "    background: #2b2f2f;\n"
            + "    border: solid 1px #a2aab0;\n"
            + "    font-size: 1em;\n"
            + "    display: inline-block;\n"
            + "    padding: 5pt;\n"
            + "}\n"
            + ".btn-copy, .btn-copy:active{\n"
            + "    width: 27pt;\n"
            + "    height: 13pt;\n"
            + "    border-radius: 3pt;\n"
            + "    float: right;\n"
            + "    margin: 0;\n"
            + "    border: solid 1px #7b7b7b;\n"
            + "    cursor: pointer;\n"
            + "    text-align: center;\n"
            + "    font-size: 9pt;\n"
            + "    color: #1a8cf0;\n"
            + "}\n"
            + ".btn-copy:active{\n"
            + "    background-color: #2d3233;\n"
            + "    text-shadow: 0px 0px 3pt #3b8a65;\n"
            + "    border: solid 1px #535353;\n"
            + "}\n"
            + ".hidden-data{\n"
            + "    width: 0px;\n"
            + "    height: 0px;\n"
            + "    position: absolute;\n"
            + "    top:0px;\n"
            + "    left: 0px;\n"
            + "    border: none;\n"
            + "    outline: none;\n"
            + "    margin: 0px;\n"
            + "    padding: 0px;\n"
            + "}\n"
            + ".code-message{\n"
            + "    display: block;\n"
            + "    visibility: hidden;\n"
            + "    padding-top: -2pt;\n"
            + "    margin-right: 20pt;\n"
            + "    margin-bottom: 6pt;\n"
            + "    color: #dbffe8;\n"
            + "    background-image: linear-gradient(to right, #4fac9fa3 , #62ff0a0a);\n"
            + "    text-align: center;\n"
            + "    padding-bottom: 2pt;\n"
            + "    padding-top: 2pt;\n"
            + "    border-radius: 3pt;\n"
            + "}\n"// added
            + ".theme-item {\n"
            + "    height: 3pt;\n"
            + "    color: white;\n"
            + "    width: 20pt;\n"
            + "    position: relative;\n"
            + "}\n"
            + ".theme-item:hover {\n"
            + "    height: 20pt;\n"
            + "    border: 1px solid #aab1b7;\n"
            + "    border-radius: 20pt;\n"
            + "}"
            + ".theme-container {\n"
            + "    cursor: pointer;\n"
            + "    left: 5pt;\n"
            + "    top: 5pt;\n"
            + "    position: absolute;\n"
            + "    display: block;\n"
            + "}";
    public static final String WIKI_STYLES_WHITE
            = "body{\n"
            + "    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Noto Sans\", Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\n"
            + "    background-color:  #fffafa;\n"
            + "    color:#303035;\n"
            + "    padding-left: 5%;\n"
            + "    padding-right: 5%;\n"
            + "}\n"
            + "a,a:hover {\n"
            + "    text-decoration: none;\n"
            + "    font-weight: bolder;\n"
            + "    color: #103c80;\n"
            + "    text-shadow: 0 0 10px #d7d7d799;\n"
            + "    vertical-align: top;\n"
            + "}\n"
            + "table {\n"
            + "    max-width: 60%;\n"
            + "    font-size: 0.9em;\n"
            + "    display: inline-table;\n"
            + "}\n"
            + "td {\n"
            + "    padding: 6pt;\n"
            + "}\n"
            + "thead{\n"
            + "    background: #eef1f7;\n"
            + "}\n"
            + "thead tr,thead td {\n"
            + "\n"
            + "\n"
            + "}\n"
            + "\n"
            + "tr{\n"
            + "    border: solid 1px #1d2831;\n"
            + "    padding: 6pt;\n"
            + "}\n"
            + "tr:nth-child(even) {\n"
            + "    background: #828da280;\n"
            + "}\n"
            + "tr:nth-child(odd) {\n"
            + "    background: #a2a2a280;\n"
            + "}\n"
            + "h1{\n"
            + "\n"
            + "}\n"
            + ".json-string{\n"
            + "    color: #0f6424;\n"
            + "}\n"
            + ".json-number{\n"
            + "    color: #bd861c;\n"
            + "}\n"
            + ".json-number{\n"
            + "    color: #bd861c;\n"
            + "}\n"
            + ".json-key{\n"
            + "    color: #14297b;    \n"
            + "}\n"
            + ".json-object,code{\n"
            + "    background: #f4f4f4a8;\n"
            + "    border: solid 1px #242d33;\n"
            + "    font-size: 1em;\n"
            + "    display: inline-block;\n"
            + "    padding: 5pt;\n"
            + "}\n"
            + ".btn-copy, .btn-copy:active{\n"
            + "    width: 27pt;\n"
            + "    height: 13pt;\n"
            + "    border-radius: 3pt;\n"
            + "    float: right;\n"
            + "    margin: 0;\n"
            + "    border: solid 1px #17568e;\n"
            + "    cursor: pointer;\n"
            + "    text-align: center;\n"
            + "    font-size: 9pt;\n"
            + "    color: #1a8cf0;\n"
            + "}\n"
            + ".btn-copy:active{\n"
            + "    background-color: #2d3233;\n"
            + "    text-shadow: 0px 0px 3pt #3b8a65;\n"
            + "    border: solid 1px #535353;\n"
            + "}\n"
            + ".hidden-data{\n"
            + "    width: 0px;\n"
            + "    height: 0px;\n"
            + "    position: absolute;\n"
            + "    top:0px;\n"
            + "    left: 0px;\n"
            + "    border: none;\n"
            + "    outline: none;\n"
            + "    margin: 0px;\n"
            + "    padding: 0px;\n"
            + "}\n"
            + ".code-message{\n"
            + "    display: block;\n"
            + "    visibility: hidden;\n"
            + "    padding-top: -2pt;\n"
            + "    margin-right: 20pt;\n"
            + "    margin-bottom: 6pt;\n"
            + "    color: #dbffe8;\n"
            + "    background-image: linear-gradient(to right, #4fac9fa3 , #62ff0a0a);\n"
            + "    text-align: center;\n"
            + "    padding-bottom: 2pt;\n"
            + "    padding-top: 2pt;\n"
            + "    border-radius: 3pt;\n"
            + "}\n"// added
            + ".theme-item {\n"
            + "    height: 3pt;\n"
            + "    color: white;\n"
            + "    width: 20pt;\n"
            + "    position: relative;\n"
            + "}\n"
            + ".theme-item:hover {\n"
            + "    height: 20pt;\n"
            + "    border: 1px solid #aab1b7;\n"
            + "    border-radius: 20pt;\n"
            + "}"
            + ".theme-container {\n"
            + "    cursor: pointer;\n"
            + "    left: 5pt;\n"
            + "    top: 5pt;\n"
            + "    position: absolute;\n"
            + "    display: block;\n"
            + "}";

    static {
        NAMED_THEMES.put("DarkGreen", WIKI_STYLES_GREEN);
        NAMED_THEMES.put("DarkBlue", WIKI_STYLES_BLUE);
        NAMED_THEMES.put("White", WIKI_STYLES_WHITE);
        
        NAMED_THEMES_FLAGS.put("DarkGreen", "#36514f");
        NAMED_THEMES_FLAGS.put("DarkBlue", "#2f3b51");
        NAMED_THEMES_FLAGS.put("White", "#FBFBFB");

    }
}
